import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import AddItemForm from "../components/AddItemForm";
import RegisterPage from "../components/Register";
import PaymentPage from "../components/Payment";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Add New Products</h1>
      <ConnectButton />
      <PaymentPage />
    </div>
  );
}

// name,
// type,
// ERC20Price,
// price,
// star,
// grade,
// description,
// image,
// have,
